version: '3.8'
services:
  redis:
    container_name: redis
    hostname: redis
    image: redis
    ports:
      - 6379:6379
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    build: .
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    links:
      - redis
    depends_on:
      redis:
        condition: service_started
